pipeline:
  name: gradle build
  identifier: gradle_build
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1690791769304
        repoName: cptekam/gradle-demo
        build: <+input>
  stages:
    - stage:
        name: gradle-build
        identifier: gradlebuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_gradle
                  identifier: Run_gradle
                  spec:
                    connectorRef: account.harnessImage
                    image: gradle:8.2
                    shell: Sh
                    command: |-
                      echo "build started for gradle project"
                      gradle build
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: chandu_doc
                    repo: cptekam/myrepo
                    tags:
                      - latest
        variables:
          - name: PLUGIN_DRY_RUN
            type: String
            description: ""
            required: false
            value: "true"
  notificationRules:
    - name: email me
      identifier: email_me
      pipelineEvents:
        - type: PipelineStart
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: PipelineEnd
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - chandra.tekam@globallogic.com
      enabled: true
